### ISSUE TITLE
AttributeError: 'SharedArray' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by SOMEAIDI** [Farama-Foundation/SuperSuit#110]
when I try the tutorial of  pistonball, I met this attribute error. But I have no idea that what should do. So what should I do to deal with the error?

**Comment by SOMEAIDI** [comment]
> Could you please provide system specs (OS, python verison, etc.) and give me your pip freeze? And did you use this file exactly? https://github.com/PettingZoo-Team/PettingZoo/blob/master/tutorials/13_lines.py

Thanks for your reply.
I perform my code on windows.And my code is :
`    env = pistonball_v4.parallel_env(n_pistons=20, time_penalty=-0.1, continuous=True, random_drop=True,
                                     random_rotate=True, ball_mass=0.75, ball_friction=0.3, ball_elasticity=1.5, max_cycles=125)
    env = ss.color_reduction_v0(env, mode='B')
    env = ss.resize_v0(env, x_size=84, y_size=84)
    env = ss.frame_stack_v1(env, 3)
    env = ss.concat_vec_envs_v0(env, 8, num_cpus=1, base_class='stable_baselines3')`

It doesn't work at all.But I find that when I remove some code :
`    env = pistonball_v4.parallel_env(n_pistons=20, time_penalty=-0.1, continuous=True, random_drop=True,
                                     random_rotate=True, ball_mass=0.75, ball_friction=0.3, ball_elasticity=1.5, max_cycles=125)
    #env = ss.color_reduction_v0(env, mode='B')
    env = ss.resize_v0(env, x_size=84, y_size=84)
    #env = ss.frame_stack_v1(env, 3)
    env = ss.concat_vec_envs_v0(env, 8, num_cpus=1, base_class='stable_baselines3')`

Now it works correctly, but I have no idea why this happen . So is Supersuit not suitable  for windows ?

**Comment by benblack769** [comment]
@jkterry1 I'll prioritize this. Of course, in the meantime, you can simply turn off multiprocessing by setting num_cpus=1

**Comment by benblack769** [comment]
This was a change in python3.8 caused by changes in the core MacOS system. See the following trail:

* python 3.8 changes default: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
* due to problem layed out here: https://bugs.python.org/issue33725
* Objective-C makes it hard to just pretend it isn't a problem and hope for the best: http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html

It might be necessary to make changes to the 13 lines tutorial as well as changes to supersuit to get this to work (putting the code after a `__name__ == "__main__"` guard).

**Comment by wittenator** [comment]
Out of curiosity:
Why is the loading and setting for pickling of the SharedArray asymmetrical at this line: https://github.com/Farama-Foundation/SuperSuit/blob/be8dcfc5856ef685239376ac3ba38809cea6ee12/supersuit/vector/utils/shared_array.py#L15 ?

I had a similar error and if I am not entirely mistaken that fixed that error for me.

**Comment by benblack769** [comment]
Ah. That would be a bug.

**Comment by benblack769** [comment]
@wittenator Thanks for pointing this out! I didn't know that it was possible for process shared data to be passed to spawn environments, but I guess they can. I went ahead and tested it in the PR and it seems to work.
