### ISSUE TITLE
MarkovVectorEnv default value for dns should be True

### ISSUE THREAD

**Issue by wittenator** [Farama-Foundation/SuperSuit#117]
While browsing through the code, something piqued my interest:
If you iterate over all possible agents in a parallel env and the agent is not present in the done dict from the last step, that should mean that the agent was removed in some step before. Currently, the default is False, which would indicate that the agent is still active. I can't think of a reason which would make sense. Do I misunderstand something or is it a bug?

This is the line I mean: https://github.com/Farama-Foundation/SuperSuit/blob/be8dcfc5856ef685239376ac3ba38809cea6ee12/supersuit/vector/markov_vector_wrapper.py#L68

**Comment by benblack769** [comment]
This isn't strictly a bug. The markov_vector_wrapper does not work out of box with environments where agents are removed. If you look here https://github.com/Farama-Foundation/SuperSuit/blob/be8dcfc5856ef685239376ac3ba38809cea6ee12/supersuit/vector/markov_vector_wrapper.py#L76 you can see that if there are agents which were removed, then the wrapper will raise an error, rather than return anything.

A commonly used fix to this problem is to apply the black death wrapper before the markov_vector_wrapper.

**Comment by benblack769** [comment]
For some background, there used to be a black_death argument to the markov_vector_wrapper, which was removed.

**Comment by wittenator** [comment]
But if the black_death flag is set, the behaviour is incorrect, right? I only resorted to using MarkovVectorEnv since it seems that the black_death wrapper and the black_death flag in the MarkovVectorEnv do very different things.

**Comment by benblack769** [comment]
Yes, it appears so.

**Comment by benblack769** [comment]
Ignore my previous message, it is actually not. In black death world, the done agents are *not* marked as done until the entire environment is over. I.e., an agent is still alive, and it still gets observations (which are all zeros, i.e. a black screen) and rewards (which are all zero) until the whole environment is terminated.

This is inspired by a terminal state in an MDP, which in many theoretical constructs is actually a recursive state that always goes back to itself.

Assuming the agent can learn that an all zeros observation is indicative of a terminal state, then it can learn that transitioning to that state will mean that there is no more reward to be found in the environment ever, which is equivalent to how RL algorithms treat the "done" flag.

**Comment by wittenator** [comment]
Ah that makes a lot of sense! But is the black death wrapper really doing the same thing? Diving into the code I didn't find the parts which set observations to zero are manage the dns.
