### ISSUE TITLE
Why is opencv-python limited to 3.4.0?

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [Farama-Foundation/SuperSuit#124]
Im creating my own module that uses opencv-python 4+ version
Currently supersuit is limited to 3.4.0, is there a reason for that?

Thanks

**Comment by jkterry1** [comment]
Just because 3.4.0 will actually install for people, and different versions are hard to install. We're planning to replace opencv with lycon2 in the near future

**Comment by jkterry1** [comment]
Not a very clean one; I'd recommend just using the newest version supersuit and overwriting the installed version of opencv if you need to
