### ISSUE TITLE
SB3 Wrapper to Access Global State

### ISSUE THREAD

**Issue by amimem** [Farama-Foundation/SuperSuit#128]
I'm trying to write a wrapper for PettingZoo MAgent environments that returns the global state of the environment instead of local observations ... my class looks like this:
```python
class MAgentWarpper(VecEnvWrapper):
    """
    :param venv: The vectorized environment
    """

    def __init__(self, venv: VecEnv, state_space):
        super().__init__(venv=venv, observation_space=state_space)

    def reset(self) -> np.ndarray:
        _ = self.venv.reset()
        return self.venv.state()

    def step_async(self, actions: np.ndarray) -> None:
        self.venv.step_async(actions)

    def step_wait(self) -> VecEnvStepReturn:
        _, reward, done, info = self.venv.step_wait()
        return self.venv.state(), reward, done, info
```

The problem is if I call it after `pettingzoo_env_to_vec_env_v1` and before `concat_vec_envs_v1`:
```python
env = {magent env}.parallel_env()
state_space = env.state_space
env = ss.pettingzoo_env_to_vec_env_v1(env)
env = MAgentWarpper(env, state_space)
env = ss.concat_vec_envs_v1(env, 1, num_cpus=0, base_class='stable_baselines3')
```
 I will get a TypeError exception:
`cannot pickle '_abc_data' object`

And if I call it after `concat_vec_envs_v1` :
```python
env = {magent env}.parallel_env()
state_space = env.state_space
env = ss.pettingzoo_env_to_vec_env_v1(env)
env = ss.concat_vec_envs_v1(env, 1, num_cpus=0, base_class='stable_baselines3')
env = MAgentWarpper(env, state_space)
```
It throws an AttributeError since `self.venv.state()` is not accessible through `ConcatVecEnv` ... Any idea how to fix this ?

**Comment by benblack769** [comment]
So the `state()` method is not a feature of the vector env API. However, it is a feature of the pettingzoo ParallelEnv API.  I would encourage you to try to create a ParallelEnv wrapper ( example here https://github.com/Farama-Foundation/SuperSuit/blob/master/supersuit/generic_wrappers/frame_skip.py#L110)

Then place that ParallelEnv wrapper before calling pettingzoo_env_to_vec_env_v1.

**Comment by jkterry1** [comment]
Hey, i'm going to close this due to inactivity and because this is a restriction in SB3 and not supersuit, please let us know if you have any additional questions though :)
