### ISSUE TITLE
opencv-python~=3.4.0 security concern

### ISSUE THREAD

**Issue by vwxyzjn** [Farama-Foundation/SuperSuit#136]
`opencv-python~=3.4.0` in the `requirements.txt` is marked as dangerous by dependabot. Could we make it `opencv-python>=3.4.0`? Is there a reason to pin it at 3.4.x?

**Comment by benblack769** [comment]
Discussion of the reason in #124. Likely now that gym's opencv is set to >=3.0, there isn't any real reason to do things differently here.

**Comment by jkterry1** [comment]
Closed because we removed opencv for tinyscalar
