### ISSUE TITLE
`concat_vec_envs_v1` prevents Python scripts from exiting 

### ISSUE THREAD

**Issue by timf34** [Farama-Foundation/SuperSuit#170]
Hi, 

When I use `concat_vec_envs_v1` when initializing my environment, the Python script will not exit. 

Even when I call `env.close()` at the end of the script, and use `sys.exit()` or similar, it still will not exit. 

Is there anything in particular I need to call to exit the script? Is this known to be an issue? 

Thanks
Tim

**Comment by jjshoots** [comment]
Hi @timf34, this may be an artifact from the fact that `concat_vec_env` uses parallel processing in Python. I think you'd need to perform a SIGINT catch:

```py
from signal import SIGINT, signal

def shutdown_handler(*_):
    print("ctrl-c invoked")
    exit(0)

if __name__ == "__main__":
    signal(SIGINT, shutdown_handler)
    ...
```

**Comment by timf34** [comment]
This unfortunately doesn't seem to work

**Comment by jjshoots** [comment]
@benblack769 Could you perhaps have a look?
