### ISSUE TITLE
Out of date error message in vector.markov_vector_wrapper

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [Farama-Foundation/SuperSuit#172]
``AssertionError: observation spaces not consistent. Perhaps you should wrap with `supersuit.aec_wrappers.pad_observations`?``
from `SuperSuit.supersuit.vector.markov_vector_wrapper:29`. `aec_wrappers` doesn't appear to exist anymore. There is a `supersuit.multiagent_wrappers.padding_wrappers.pad_observations_v0`. I'm not sure if this is the same as I still get issues using (likely user error). 

I'm new to both pettingzoo and supersuit, so I'm not sure about the intended behavior/paths.

**Comment by jjshoots** [comment]
Heya, thanks for this! Yes this is indeed a bug and related to parts od the code being updated while others remain stagnant. I'll make a PR fixing it.

**Comment by jjshoots** [comment]
Hey @Benjamin-Etheredge, just checking, do you still have issues with your code?
