### ISSUE TITLE
[Progress] Truncation Termination API Update

### ISSUE THREAD

**Issue by jjshoots** [Farama-Foundation/SuperSuit#176]
# About

As part of the Gym update to 0.25, the following changes have been made:

`done` -> `termination` and `truncation`

The singular `done` signal has been changed to a `termination` and `truncation` signal, where `termination` dictates that the environment has ended due to meeting certain conditions, and `truncation` dictates that the environment has ended due to exceeding the time/frame limit

## Progress

The road plan for this update is as follows:

1. Truncation/Termination update
    - [ ] AEC Vector
    - [ ] Generic Wrappers
    - [x] Lambda Wrappers
    - [ ] Multiagent Wrappers
    - [ ] Utils
    - [ ] Vector
2. Tests update
    - [x] `vec_env_test.py`
    - [x] `test_autodep.py`
    - [ ] `pettingzoo_api_test.py`
    - [x] `parallel_env_test.py`
    - [ ] `gym_unwrapped_test.py`
    - [ ] `gym_mock_test.py`
    - [ ] `generated_agents_test.py`
    - [x] `aec_unwrapped_test.py`
    - [x] `aec_mock_test.py`
    - [ ] `test_vector/`
    - [ ] `test_utils/`

**Comment by WillDudley** [comment]
Had some time to kill, started looking at AEC Vector wrappers, but haven't done any refactoring yet. (https://github.com/WillDudley/SuperSuit/tree/API_Update_aec_wrappers_test)
