### ISSUE TITLE
render method: signature mismatch

### ISSUE THREAD

**Issue by adam-crowther** [Farama-Foundation/SuperSuit#223]
Hi,

First some observations:
- SuperSuit class `SB3SecEnvWrapper` inherits from Baselines3 parent class `VecEnvWrapper`.  
- `VecEnvWrapper` provides the following render() method:
   ```python
      def render(self, mode: Optional[str] = None) -> Optional[np.ndarray]:
          return self.venv.render(mode=mode)
   ```
- Internally,  `SB3SecEnvWrapper` wraps an instance of `ConcatVecEnv`, which provides the following render() method:
   ```python
      def render(self):
          return self.vec_envs[0].render()
   ```
- So `env = ss.concat_vec_envs_v1(env, 1, base_class='stable_baselines3')` wraps my env in a `SB3SecEnvWrapper`, which in turn wraps a  `ConcatVecEnv`.  When I call `env.render()` on my environment, I get the following error:

```console
TypeError: ConcatVecEnv.render() got an unexpected keyword argument 'mode'
```

Looking at commit history it seems that the `mode` parameter did actually exist in the `ConcatVecEnv` wrapper up till release 3.6.0:
https://github.com/Farama-Foundation/SuperSuit/blob/9b661380036e53ed338b257406dd2c32ed67d5f5/supersuit/vector/concat_vec_env.py#L112C1-L114C1
But it was removed in release 3.7.0:
https://github.com/Farama-Foundation/SuperSuit/blob/ac2a2511bfa2bd268965eb6d7b54e3b9d5a3b48b/supersuit/vector/concat_vec_env.py#L112-L114C1
This change broke the `env.render()` method when it is wrapped with `ss.concat_vec_envs_v1(env, 1, base_class='stable_baselines3')`.

I need the render method because I'm using the Baselines3 EvalCallback, and I want to generate PNGs of my env for each evaluation episode.  (This works in pure Baselines3).

I can't shim this, because the `SB3SecEnvWrapper` sets up the `ConcatVecEnv` wrapper internally.  For now I will have to clone your repo and hack the `mode` parameter back in to the `ConcatVecEnv` wrapper.

Thanks for your help,

Adam

**Comment by adam-crowther** [comment]
I managed to hack it locally by cloning the SuperSuit repo and changing the signature of the `render()` methods, adding back the `mode` parameter where neccessary:

```python
class ConcatVecEnv:
...
    def render(self, mode: Optional[str] = None) -> Optional[np.ndarray]:
        return self.vec_envs[0].render(mode)


class ProcConcatVec:
...
    def render(self, mode: Optional[str] = None) -> Optional[np.ndarray]:
        self.pipes[0].send("render")
        render_result = self.pipes[0].recv()

        if isinstance(render_result, tuple):
            e, tb = render_result
            print(tb)
            raise e

        return render_result


class SingleVecEnv:
...
    def render(self, mode: Optional[str] = None) -> Optional[np.ndarray]:
        return self.gym_env.render(mode)
        
class MarkovVectorEnv:
...
    def render(self, mode: Optional[str] = None) -> Optional[np.ndarray]:
        return self.par_env.render()
```

**Note that that last one does NOT pass the mode parameter to the wrapped env, but just drops it.**  I know this is a fugly hack, and I'm not saying this is how the issue should be fixed,  My intention here is just to give you as much information as possible.

**Comment by elliottower** [comment]
Hey Adam, thanks a lot for bringing this up, I will go through and try to make things as consistent as possible. Our SB3 wrapper should most definitely have the same signature as its superclass.

**Comment by elliottower** [comment]
I believe this was completed with the above PR but if there are still any inconsistencies/issues please let me know
