### ISSUE TITLE
Is it possible to convert an AEC Environment with an Action_Mask to a Vector_Env in SuperSuit? (So it works well with Stable-Baselines3)

### ISSUE THREAD

**Issue by akshaygh0sh** [Farama-Foundation/SuperSuit#96]
So, I have a custom AEC Environment written in PettingZoo that has an action_mask (it's a board game with a large amount of "legal moves"; so it's necessary to mask out illegal moves during training), but when I try to vectorize this aec_env I get the following error:

```
~\AppData\Local\Temp/ipykernel_15820/1366347090.py in <module>
      4 import supersuit as ss
      5 
----> 6 env = ss.vectorize_aec_env_v0(env, num_envs = 8, num_cpus = 4)
      7
~\AppData\Roaming\Python\Python37\site-packages\supersuit\aec_vector\create.py in vectorize_aec_env_v0(aec_env, num_envs, num_cpus)
     13         return SyncAECVectorEnv(env_list)
     14     else:
---> 15         return AsyncAECVectorEnv(env_list, num_cpus)

~\AppData\Roaming\Python\Python37\site-packages\supersuit\aec_vector\async_vector_env.py in __init__(self, env_constructors, num_cpus, return_copy)
    254                 SpaceWrapper(self.action_spaces[agent]),
    255             )
--> 256             for agent in self.possible_agents
    257         }
    258 

~\AppData\Roaming\Python\Python37\site-packages\supersuit\aec_vector\async_vector_env.py in <dictcomp>(.0)
    254                 SpaceWrapper(self.action_spaces[agent]),
    255             )
--> 256             for agent in self.possible_agents
    257         }
    258 

~\AppData\Roaming\Python\Python37\site-packages\supersuit\aec_vector\async_vector_env.py in __init__(self, space)
     22             self.low = space.low
     23         else:
---> 24             assert False, "ProcVectorEnv only support Box and Discrete types"
     25 
     26 

AssertionError: ProcVectorEnv only support Box and Discrete types
```

For reference, the action_space and the observation_space (which I suspect is the cause of this error due to the prescence of the action_mask and the fact that it is a Dict instead of mapping directly to a gym.Space) of my environment are as follow: 

`self.action_spaces = {name: spaces.Discrete(4672) for name in self.possible_agents}
 self.observation_spaces = {name: spaces.Dict({
            'observation': spaces.Box(low=-1, high=500, shape=(5, 8, 8, 14), dtype=np.int16),
            'action_mask': spaces.Box(low=0, high=1, shape=(4672,), dtype=np.int8)
        }) for name in self.possible_agents}`

Is there a way to convert my AEC Environment with an action_mask to a vector_env so I can use it to train with stable-baselines3 (specifically with PPO with a CNN)? If not, could you offer me some alternatives to train my environment with (I am basically a beginner in RL and I would love some advice on some libraries that have easy trainers with common RL algorithms like PPO with native CNN support).

Thanks for your help.

**Comment by benblack769** [comment]
Unfortunately, supporting dictionary spaces with supersuit's vectorization code is a bit difficult. We would welcome a PR for this.
While that would fix the crash you are running into now, it still would not allow for proper action mask support.

The only libraries I know of with reasonable support for both action masking and dictionary observations are 1) Rllib ([see this example of mine](https://gist.github.com/benblack769/7ea33e31d31a819d25bf64fb2bf1d430)) and 2) tianshou ([see [this issue](https://github.com/thu-ml/tianshou/issues/381) for an example of self-play, note that we know of a bug in tianshou's multiplayer support, but hopefully that  will be resolved soon).

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity

**Comment by benblack769** [comment]
I would like to keep this open as a feature request, as it is one of the more complicated features I hope to support one day.

**Comment by elliottower** [comment]
I have some tutorials using AEC environments with actions masks with SB3, it's not the most straightforward or clean but it works: https://pettingzoo.farama.org/main/tutorials/sb3/connect_four/
